name: Compile IPK

on:
  push:
    paths:
      - 'luci-app-radmon-php7/Makefile'
      - 'luci-app-radmon-php8/Makefile'
  workflow_dispatch:

jobs:
  build:
    name: Compile IPK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment
      run: |
        sudo -E apt-get update > /dev/null 2>&1
        sudo -E apt-get install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget > /dev/null 2>&1
        sudo -E apt-get autoremove --purge > /dev/null 2>&1
        sudo -E apt-get clean > /dev/null 2>&1
        wget https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz > /dev/null 2>&1
        tar xJf openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz > /dev/null 2>&1
        mv openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64 sdk > /dev/null 2>&1

    - name: Setup feeds
      run: |
        cd sdk
        ./scripts/feeds update -a > /dev/null 2>&1
        ./scripts/feeds install -a > /dev/null 2>&1

    - name: Get Radmon PHP7
      id: get_radmon_php7
      run: |
        cd luci-app-radmon-php7
        echo "radmon_php7=$(grep 'PKG_VERSION:=' Makefile | awk -F '=' '{print $2}' | tr -d ' ')" >> $GITHUB_OUTPUT

    - name: Prepare Radmon PHP7
      run: |
        cd sdk
        mkdir -p package/luci-app-radmon-php7
        cp -R ../luci-app-radmon-php7/* package/luci-app-radmon-php7/

    - name: Build Radmon PHP7
      id: build_php7
      run: |
        cd sdk && make defconfig > /dev/null 2>&1
        sed -i 's/CONFIG_LUCI_SRCDIET=y/# CONFIG_LUCI_SRCDIET is not set/' .config
        sed -i 's/CONFIG_LUCI_JSMIN=y/# CONFIG_LUCI_JSMIN is not set/' .config
        sed -i 's/CONFIG_LUCI_CSSTIDY=y/# CONFIG_LUCI_CSSTIDY is not set/' .config
        sed -i 's/# CONFIG_NO_STRIP is not set/CONFIG_NO_STRIP=y/' .config
        sed -i 's/CONFIG_USE_STRIP=y/# CONFIG_USE_STRIP is not set/' .config
        sed -i 's/CONFIG_USE_SSTRIP=y/# CONFIG_USE_SSTRIP is not set/' .config
        (make package/luci-app-radmon-php7/compile V=s -j$(nproc) || echo "BUILD_FAILED=true" >> $GITHUB_ENV) > /dev/null 2>&1

    - name: List Output Directory
      run: |
        ls -l bin/packages/x86_64/luci/
    
    - name: Check Failed Radmon PHP7
      if: env.BUILD_FAILED != 'true'
      run: |
        if [ -f "bin/packages/x86_64/luci/luci-app-radmon-php7_${{ steps.get_radmon_php7.outputs.radmon_php7 }}_all.ipk" ]; then
          mv bin/packages/x86_64/luci/luci-app-radmon-php7_${{ steps.get_radmon_php7.outputs.radmon_php7 }}_all.ipk ../luci-app-radmon-php7_${{ steps.get_radmon_php7.outputs.radmon_php7 }}_all.ipk
        else
          echo "File IPK untuk PHP7 tidak ditemukan."
          exit 1
        fi

    - name: Get Ramon PHP8
      id: get_radmon_php8
      run: |
        cd luci-app-radmon-php8
        echo "radmon_php8=$(grep 'PKG_VERSION:=' Makefile | awk -F '=' '{print $2}' | tr -d ' ')" >> $GITHUB_OUTPUT

    - name: Prepare Radmon PHP8
      run: |
        cd sdk
        mkdir -p package/luci-app-radmon-php8
        cp -R ../luci-app-radmon-php8/* package/luci-app-radmon-php8/

    - name: Build Radmon PHP8
      id: build_php8
      run: |
        cd sdk && make defconfig
        sed -i 's/CONFIG_LUCI_SRCDIET=y/# CONFIG_LUCI_SRCDIET is not set/' .config
        sed -i 's/CONFIG_LUCI_JSMIN=y/# CONFIG_LUCI_JSMIN is not set/' .config
        sed -i 's/CONFIG_LUCI_CSSTIDY=y/# CONFIG_LUCI_CSSTIDY is not set/' .config
        sed -i 's/# CONFIG_NO_STRIP is not set/CONFIG_NO_STRIP=y/' .config
        sed -i 's/CONFIG_USE_STRIP=y/# CONFIG_USE_STRIP is not set/' .config
        sed -i 's/CONFIG_USE_SSTRIP=y/# CONFIG_USE_SSTRIP is not set/' .config
        (make package/luci-app-radmon-php8/compile V=s -j$(nproc) || echo "BUILD_FAILED=true" >> $GITHUB_ENV) > /dev/null 2>&1

    - name: Check Failed Radmon PHP8
      if: env.BUILD_FAILED != 'true'
      run: |
        if [ -f "bin/packages/x86_64/luci/luci-app-radmon-php8_${{ steps.get_radmon_php8.outputs.radmon_php8 }}_all.ipk" ]; then
          mv bin/packages/x86_64/luci/luci-app-radmon-php8_${{ steps.get_radmon_php8.outputs.radmon_php8 }}_all.ipk ../luci-app-radmon-php8_${{ steps.get_radmon_php8.outputs.radmon_php8 }}_all.ipk
        else
          echo "File IPK untuk PHP7 tidak ditemukan."
          exit 1
        fi
        
    - name: Create Release
      if: env.BUILD_FAILED != 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        release_date=$(date +'%Y.%m.%d')
        release_name="${{ steps.get_radmon_php7.outputs.radmon_php7 }}"
        release_tag="${release_date}"

        gh release create "$release_tag" \
          --title "$release_tag" \
          --generate-notes=false

    - name: Upload PHP7 IPK
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        gh release upload ${{ steps.get_radmon_php7.outputs.radmon_php7 }} \
          ./luci-app-radmon-php7_${{ steps.get_radmon_php7.outputs.radmon_php7 }}_all.ipk

    - name: Upload PHP8 IPK
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        gh release upload ${{ steps.get_radmon_php8.outputs.radmon_php8 }} \
          ./luci-app-radmon-php8_${{ steps.get_radmon_php8.outputs.radmon_php8 }}_all.ipk
