name: Build Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'luci-app-radmon-php7/**'
      - 'luci-app-radmon-php8/**'

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          - aarch64_generic
        tag:
          - openwrt-23.05
          - openwrt-21.02
        packages:
          - luci-app-radmon-php7
          - luci-app-radmon-php8

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.tag }}
          PACKAGES: ${{ matrix.packages }}
          NO_REFRESH_CHECK: true

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/msd/*.ipk
