name: Build Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'luci-app-radmon-php7/**'
      - 'luci-app-radmon-php8/**'

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: [openwrt-21.02, openwrt-23.05]
        package: [luci-app-radmon-php7, luci-app-radmon-php8]
        include:
          - tag: openwrt-21.02
            package: luci-app-radmon-php7
          - tag: openwrt-23.05
            package: luci-app-radmon-php8
        arch:
          - x86_64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.tag }}
          PACKAGES: ${{ matrix.package }}
          NO_REFRESH_CHECK: true

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-${{ matrix.tag }}
          path: bin/packages/${{ matrix.arch }}/msd/*.ipk
